### ISSUE TITLE
Timezone support

### ISSUE THREAD

**Issue by borut-t** [erica/NSDate-Extensions#51]
I've just found that all date calculations happens with timezone specified in current calendar e.g. `[NSCalendar currentCalendar]`. But when you are working with time in different timezones, it become more or less useless.

It would be great if you could set the timezone for calendar. Something like that:
`[CURRENT_CALENDAR setTimeZone:[NSTimeZone timeZoneWithAbbreviation:@"UTC"]];`

Thanks!

**Comment by erica** [comment]
I'm sticking with currentCalendar just because that's the most common use-case and I use it ridiculously widely. I understand the different timezone challenge but these are very practical use-cases and I'm afraid it falls slightly out of my brief.
