### ISSUE TITLE
IOS7 week NS_CALENDAR_DEPRECATED

### ISSUE THREAD

**Issue by p709723778** [erica/NSDate-Extensions#52]
- (NSInteger)week NS_CALENDAR_DEPRECATED(10_4, 10_9, 2_0, 7_0, "Use weekOfMonth or weekOfYear, depending on which you mean");

ios7 above can not be used

- (NSInteger)week
{
    NSDateComponents *components = [[NSDate currentCalendar] components:componentFlags fromDate:self];

    return components.week;
}

**Comment by erica** [comment]
handled in https://github.com/erica/SwiftDates
