### ISSUE TITLE
"week" Propertie Version Support

### ISSUE THREAD

**Issue by p709723778** [erica/NSDate-Extensions#54]
SDK IOS7.1 Above Versions

- (NSInteger) week
{
	NSDateComponents *components = [[NSDate currentCalendar] components:componentFlags fromDate:self];
	return components.week;
}

Should be replaced

- (NSInteger) week
{
	NSDateComponents *components = [[NSDate currentCalendar] components:componentFlags fromDate:self];
	return components.weekOfYear;
}

Precautions:
componentFlags add  "NSWeekOfYearCalendarUnit"

**Comment by erica** [comment]
I've broken them all out separately now

https://github.com/erica/SwiftDates
