### ISSUE TITLE
Need the pod update

### ISSUE THREAD

**Issue by KiritoStudio** [erica/NSDate-Extensions#71]
The pod 'NSDate-Extensions' version is not the latest one, could you please update it?

**Comment by erica** [comment]
I've never done a pod.

-- E

**Comment by KiritoStudio** [comment]
@erica But I found it in pod search:
![image](https://cloud.githubusercontent.com/assets/553215/17936051/0f9dd24c-6a50-11e6-97ce-0c6d8bf713ef.png)

**Comment by erica** [comment]
I am not disputing that. But I have never done a pod.

-- E
